# Generated by Django 4.2.4 on 2023-10-26 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('amount_saved', models.PositiveIntegerField()),
                ('amount_off', models.PositiveIntegerField()),
                ('purchases', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=250, null=True)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('address', models.CharField(max_length=30, null=True)),
                ('lga', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('about', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('wallet', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='seller_logo/default.jpg', upload_to='seller_logo')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=250)),
                ('business_phone', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBackgroundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_photo', models.ImageField(default='background_photos/default.jpg', upload_to='background_photos')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_photo', models.ImageField(default='product_photos/default.jpg', upload_to='product_photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.bulkproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bulkoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.bulkoption')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.buyer')),
            ],
            options={
                'unique_together': {('buyer', 'bulkoption')},
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_cart',
            field=models.ManyToManyField(blank=True, through='landing.Cart', to='landing.bulkoption'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='landing.productcategory'),
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.seller'),
        ),
        migrations.AddField(
            model_name='bulkoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.bulkproduct'),
        ),
    ]
