# Generated by Django 4.2.4 on 2023-10-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_stage', models.CharField(choices=[('Pooling', 'Pooling'), ('Pending', 'Pending'), ('In_transit', 'In_transit'), ('delivered', 'delivered')], max_length=11)),
                ('pooled_at', models.DateTimeField(auto_now_add=True)),
                ('pending_at', models.DateTimeField(auto_now_add=True)),
                ('in_transit_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('bulkoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.bulkoption')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.buyer')),
            ],
        ),
    ]
