# Generated by Django 4.2.4 on 2023-10-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cart_amount_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_cart',
            field=models.ManyToManyField(blank=True, related_name='buyer_cart', through='landing.Cart', to='landing.bulkoption'),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('bulkoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.bulkoption')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.buyer')),
            ],
            options={
                'unique_together': {('buyer', 'bulkoption')},
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_pool',
            field=models.ManyToManyField(blank=True, related_name='buyer_pool', through='landing.Pool', to='landing.bulkoption'),
        ),
    ]
